
/**
 * Represents the user-defined weightages for the investment thesis.
 * Each property corresponds to a key analysis category.
 */
export interface Weightages {
    /** The importance weight for the founding team (0-100). */
    team: number;
    /** The importance weight for the product/technology (0-100). */
    product: number;
    /** The importance weight for the market size and opportunity (0-100). */
    market: number;
    /** The importance weight for business traction and metrics (0-100). */
    traction: number;
}

/**
 * Defines the structure of the investment analysis report generated by the AI.
 */
export interface AnalysisReport {
    /** The name of the startup being analyzed. */
    startupName: string;
    /** A concise executive summary of the investment opportunity. */
    summary: string;
    /** A list of key strengths identified in the analysis. */
    keyStrengths: string[];
    /** A list of key risks and potential red flags. */
    riskAssessment: string[];
    /** A comparative analysis against sector peers. */
    benchmarkAnalysis: string;
    /** An assessment of the startup's growth potential. */
    growthPotential: string;
    /** The final investment recommendation based on the analysis and weightages. */
    recommendation: 'Strong Recommend' | 'Recommend' | 'Pass' | 'Strong Pass';
    /** An overall score (0-100) reflecting the investment opportunity's quality. */
    overallScore: number;
}
